renamed the workflow

diff --git a/.github/workflows/app_deploy.yml b/.github/workflows/app_deploy.yml
--- a/.github/workflows/app_deploy.yml
+++ b/.github/workflows/app_deploy.yml
@@ -1,4 +1,4 @@
-name: "Run The Ansible Role: App Deploy"
+name: "App Deploy"
 
 on:
   workflow_dispatch:
@@ -62,7 +62,7 @@ jobs:
         run: |
           CURRENT=$(kubectl get deployment frontend -n "${{ secrets.K8S_NAMESPACE_NAME }}" -o jsonpath='{.spec.template.spec.containers[0].image}')
           if [ -z "$CURRENT" ]; then
-            echo "❌ Could not fetch current frontend image!" >&2
+            echo "Could not fetch current frontend image!" >&2
             exit 1
           fi
           echo "FRONTEND_IMAGE=$CURRENT" >> $GITHUB_ENV
@@ -77,7 +77,7 @@ jobs:
         run: |
           CURRENT=$(kubectl get deployment backend -n "${{ secrets.K8S_NAMESPACE_NAME }}" -o jsonpath='{.spec.template.spec.containers[0].image}')
           if [ -z "$CURRENT" ]; then
-            echo "❌ Could not fetch current backend image!" >&2
+            echo "Could not fetch current backend image!" >&2
             exit 1
           fi
           echo "BACKEND_IMAGE=$CURRENT" >> $GITHUB_ENV
